### ISSUE TITLE
persisted file workspace file .vscode/.cmaketools.json contains invalid setting

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#34]
On my test machine, the default setting
`"cmake.initialBuildType": "Debug"`
is unchanged, i.e., not overwritten by a user or workspace setting.

I do a clean "cmake configure" step of our project.

After that, the persisted workspace file `.vscode/.cmaketools.json` contains the invalid setting
`{"selectedBuildType":"None"}`
. Expected is:
`{"selectedBuildType":"Debug"}`
I guess that your implementation is as follows:
- initialize that file with "None"
- launch "cmake configure" step
- if that returns with errorcode 0, i.e. "ok", update that file with "Debug", otherwise leave untouched.

However, expected behaviour would be:
- initialize that file with the value of configuration variable `cmake.initialBuildType`
- only change the contents of file `.vscode/.cmaketools.json` when the user switches between the build type manually, e.g. to "Debug" or to "Release"
- do not make the contents of that file dependent on the errorcode return value of the cmake run for "configure".

Why am I asking this?
Because in the current situation, the wrong value will be present in the persisted file
if the "cmake configure" step fails. If that happens for a user, and he shuts down and restarts
VSCode (for example when leaving work in the evening and coming back the next morning),
and does not remember that the "configure" step failed, then a build will be launched for 
build variant "None" instead of "Debug", producing a completely different build result.

**Comment by vector-of-bool** [comment]
This ``initialBuildType`` settings is proving to be a lot more complicated to get right than it sounds. The ``.cmaketools.json`` was added recently, and I thought I had tried to see how it played with ``initialBuildType`` exhaustively (Apparently not enough). I'll get on this one.

**Comment by MinnieTheMoocher** [comment]
I would completely do away with that persisted setting.
It in fact models a mini state engine of your plugin, i.e.,
the value "None" means "user has not yet run cmake configure".
All that is not necessary.
The setting `cmake.initialBuildType` already now can be used to decide if you want a "Release"
or "Debug" build. And exactly that should occur when the user launches "cmake configure"
or "build". There is no need IMHO to track his decision in _another_, persisted setting.

**Comment by MinnieTheMoocher** [comment]
Ugh, may I raise the prio of this, please?
This wrong setting currently completely prevents a correct build for me.
The initial (wrong) value "None" is put into the persisted setting, leading to the cmake command line 
option -DCMAKE_BUILD_TYPE=None during the "configure" step, which breaks the build.
:'(

**Comment by vector-of-bool** [comment]
Okay, I'll get on this. Could you give me detailed repro steps? I though I tried this exhaustively, but apparently not.

In order to support other features, the extension must have some extra data about what the build type is, in order to support the substitution of ``${buildType}`` in, ie. the ``buildDirectory`` setting. I'll rework the login around the handling of that file to be a bit more robust.

**Comment by vector-of-bool** [comment]
Should be fixed in 0.4.2, I should've gotten it all this time.

**Comment by MinnieTheMoocher** [comment]
I still can't see why persisting this setting in file `.cmaketools.json` should be necessary!
Why?
But it works now.

**Comment by vector-of-bool** [comment]
It is necessary because of being able to templatize ``cmake.buildDirectory`` with ``${buildType}``. Before this change, it was sufficient to just use the ``CMakeCache.txt`` to look up the build type, but now it is necessary to store the user's build type in some other fashion because the location of ``CMakeCache.txt`` cannot be reliably determined without already knowing the build type. If a user closes Code and then restarts again, I'd like to be able to know what build type they were previously using so that I can resume exactly where I left off. In the future, more values will be committed to this file for more rich CMake project management.
